#!/usr/bin/env zsh

# 1. Definimos las opciones como un array simple
local -a sub_params
sub_params=(all)

local REAL_USER="pato"
local USER_ID=$(id -u $REAL_USER)

# Buscamos '--list' en todos los argumentos recibidos ($*)
if [[ " $* " == *" --list "* ]]; then
    echo "${(j: :)sub_params}"
    return 0
fi

# 3. Lógica del comando
case "$1" in
    all)
        echo "-------------------------------------------"
        echo "📸 Alfred: Limpiando el sistema..."
        echo "-------------------------------------------"

        # 1. Mantenimiento de paquetes (APT)
        sudo apt-get autoremove -y
        sudo apt-get autoclean -y
        sudo apt-get clean

        # 2. Limpieza de Docker (Imágenes, contenedores y redes sin uso)
        # Borra TODO lo que no se use y tenga más de 7 días
        docker system prune -af --filter "until=168h"

        # 3. Gestión de logs de Systemd (Límite a 500MB)
        sudo journalctl --vacuum-size=500M

        # 4. Limpieza de Flatpak (si está instalado)
        if command -v flatpak &> /dev/null; then
            flatpak uninstall --unused -y
        fi

        # 5. Limpieza de cachés de usuario (Miniaturas y temporales)
        rm -rf ~/.cache/thumbnails/*
        # Opcional: Limpiar caché general de usuario (cuidado con apps abiertas)
        # rm -rf ~/.cache/*

        # 7. Limpieza de archivos temporales del sistema
        sudo rm -rf /tmp/*
        sudo rm -rf /var/tmp/*


	# 4. Notificación final
    if [ $? -eq 0 ]; then
       	# Si todo ha ido bien
		alfred_notify "Limpieza completada con éxito." "utilities-terminal"
	else
       	# Si algo falló en el último comando
         alfred_notify "Ojo, algo no ha salido bien" "dialog-error"
	fi
	    ;;
    *)
        echo "Uso: alfred clean {${(j:|:)sub_params}}"
        return 1
        ;;
esac
